- name: kubectl-get
  alias: [kget, kgetall]
  syntax: |
    kubectl get pods                 # list pods in current ns
    kubectl get svc                  # list services
    kubectl get nodes               # list nodes
    kubectl get all --all-namespaces # get everything
  description: Basic kubectl get commands to explore Kubernetes objects

- name: kubectl-apply
  alias: [kapply]
  syntax: |
    kubectl apply -f pod.yaml       # apply config file
    kubectl apply -k ./myfolder     # apply kustomize folder
  description: Apply manifests to cluster

- name: kubectl-delete
  alias: [kdel]
  syntax: |
    kubectl delete pod mypod        # delete single pod
    kubectl delete -f deployment.yaml # delete from manifest
  description: Delete K8s resources

- name: kubectl-describe
  alias: [kdesc]
  syntax: |
    kubectl describe pod mypod      # details of pod
    kubectl describe node mynode    # node info
  description: Show detailed state of resources

- name: kubectl-logs
  alias: [klogs]
  syntax: |
    kubectl logs mypod              # logs from pod
    kubectl logs mypod -c mycontainer # logs from specific container
    kubectl logs -f mypod           # stream logs
    kubectl logs --previous mypod  # get logs from previous pod crash
  description: View logs from pods/containers

- name: kubectl-exec
  alias: [kexec]
  syntax: |
    kubectl exec -it mypod -- /bin/bash  # exec into pod
    kubectl exec mypod -- ls /           # run command in pod
  description: Execute command inside running pod

- name: kubectl-port-forward
  alias: [kpf]
  syntax: |
    kubectl port-forward svc/myservice 8080:80   # svc forward
    kubectl port-forward pod/mypod 8080:80       # pod forward
  description: Forward local port to pod/service

- name: kubectl-cp
  alias: [kcp]
  syntax: |
    kubectl cp mypod:/path/in/pod /local/path    # copy from pod
    kubectl cp /local/path mypod:/path/in/pod    # copy to pod
  description: Copy files to/from containers

- name: kubectl-ns
  alias: [kns]
  syntax: |
    kubectl get ns                    # list namespaces
    kubectl config set-context --current --namespace=my-namespace  # switch ns
  description: Namespace management

- name: kubectl-create
  alias: [kcreate]
  syntax: |
    kubectl create deployment nginx --image=nginx         # create deployment
    kubectl create service clusterip mysvc --tcp=80:80     # create svc
    kubectl create configmap mycfg --from-literal=key=val  # create configmap
  description: Imperative creation of K8s objects

- name: kubectl-autoscale
  alias: [kauto]
  syntax: |
    kubectl autoscale deployment nginx --cpu-percent=50 --min=1 --max=5  # HPA setup
  description: Horizontal Pod Autoscaler via kubectl

- name: kubectl-rollout
  alias: [kroll]
  syntax: |
    kubectl rollout status deployment/nginx     # rollout status
    kubectl rollout history deployment/nginx    # rollout history
    kubectl rollout undo deployment/nginx       # undo to previous
  description: Manage deployment rollouts

- name: kubectl-scale
  alias: [kscale]
  syntax: |
    kubectl scale deployment nginx --replicas=5 # scale pods manually
  description: Manually scale deployments

- name: kubectl-edit
  alias: [kedit]
  syntax: |
    export KUBE_EDITOR="nano"                  # set kube editor as nano
    kubectl edit deployment nginx              # edit live resource
  description: Open resource in editor to edit live config
  
- name: kubeadm
  alias: [kadm,kubeadm]
  syntax: |
    kubeadm init --pod-network-cidr=10.244.0.0/16  # init master node
    kubeadm token create --print-join-command      # Create token
    kubeadm join <master-ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
    kubeadm reset --force             # reset cluster config
  description: Kubeadm commands

